apiVersion: v1
kind: Service
metadata:
  name: racks-app
  namespace: racks
spec:
  type: NodePort
  selector:
    app: racks-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
