#Sensitive
apiVersion: v1
kind: Secret
metadata:
  name: racks-secret
  namespace: racks
type: Opaque
stringData:
  POSTGRES_DB: racks_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mich

  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/racks_db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: mich
